[package]
name = "endgame"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"          # For cryptographic randomness
sha2 = "0.10"         # For hash functions
rayon = "1.7"         # For parallelization
